env:
  - CGO_ENABLED=0
  - PROJECT=github.com/openrport/rport-pairing
builds:
  - id: rport-pairing
    main: ./cmd/rport-pairing.go
    ldflags:
      - "-s -w -X main.Version={{.Version}}"
    binary: rport-pairing
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: rport-pairing
    name_template: "rport-pairing_{{ .Os }}_{{ .Arch }}"
    builds:
      - rport-pairing
    files:
      - rport-pairing.conf.example
      - rport-pairing.service
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: openrport
    name: rport-pairing
  draft: false
  prerelease: true
